build:
    tests:
        override:
            -
                command: './vendor/bin/phpunit tests --coverage-clover=log-coverage'
                coverage:
                    file: 'log-coverage'
                    format: 'clover'
