
build:
    environment:
        php: '5.6'
        mysql: '5.7'
        hosts:
            winners.dev: '127.0.0.1'
        variables:
            APP_KEY: 'base64:OYl4Bk9ekouOUIRXyeTD0FVi+cJ9D+HMyDJBgSBSUuI='
            APP_ENV: 'testing'
            APP_URL: 'http://winners.dev'
            API_HOST: 'winners.dev'
            DB_HOST: '127.0.0.1'
            DB_DATABASE: 'scrutinizer'
            DB_USERNAME: 'root'
            DB_PASSWORD: ''
            MAIL_DRIVER: 'log'
    cache:
        directories:
            - vendor/
            - ~/.composer/cache/
    dependencies:
        before:
            - mysql -uroot -e 'CREATE DATABASE scrutinizer'
    tests:
        before:
            - chmod -R 777 storage
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=laravel-test-examples-coverage
                coverage:
                    file: laravel-test-examples-coverage
                    format: clover